### ISSUE TITLE
# > A inserts unwanted space code points

### ISSUE THREAD

**Issue by iwsfutcmd** [r12a/uniview#12]
If the user inserts a string consisting of multiple code points into the text box, presses the [A > #] button, and then presses the [# > A] button, the result has spaces (U+0020) inserted in between each code point. 

Steps to reproduce:

1. Type "abc" into the text box, and press [A > #]
2. Observe text box is now "0061 0062 0063"
3. Press [# > A]
4. Observe text box is now "a b c"

**Comment by r12a** [comment]
Just refound this comment.  This is a tricky one.  Actually, the converter seeks out potential code point values, even if expressed as escapes.  So, for example, the following:

[1] `Here's a sample: 0061 0062 0063`
[2] `Here's a sample: &x#0061; &x#0062; &x#0063;`

will both produce:

`Here's a sample: a b c`

In this kind of sentence-like conversion it's important to retain the spaces.

Note that you can produce Here's a sample: abc by using
`Here's a sample: \u0061\u0062\u0062`

or other escapes, such as the HTML ones shown earlier, or several more.

All this was done so that one could paste a sentence from the Unicode Core spec and replace the numbers with characters. Eg.

`The consonant clusters kXa and jña are represented by the sequences <U+1140E
newa letter ka, U+11442 newa sign virama, U+11432 newa letter ssa> and
<U+11416 newa letter ja, U+11442 newa sign virama, U+11423 newa letter na>,
respectively.`

becomes

`The consonant cl sters kXa and jña are represented by the sequences < 𑐎 newa letter ka, 𑑂 newa sign virama, 𑐲 newa letter ssa> and < 𑐖 newa letter ja, 𑑂 newa sign virama, 𑐣 newa letter na>, respectively.`

Hopefully, people won't too often convert one way, then immediately try to revert it.  However, if they do, it's possible to achieve the result you wanted by clicking on the 
<img src="https://github.com/r12a/uniview/assets/4839211/98eb2e48-d45c-4a8b-affd-252ee4d8a33c" alt="delete spaces" style="height:1rem; width:1rem;">
icon, to remove the spaces after the conversion.

Closing this, in the hope that i convinced you...
