### ISSUE TITLE
Clarify characters

### ISSUE THREAD

**Issue by VincentWo** [r12a/uniview#13]
Characters isn't a well defined term in the Unicode Standard so this should probably be replaced with "Code Points" or "Unicode Code Points"

**Comment by ghost** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by r12a** [comment]
Not sure which text is the issue here, but there are some places where i chose the term 'characters' to be less specific and more user-friendly.  In those cases i think there's no harm done. (I'm very much aware of the importance of using more specific terms where it matters, such as in specifications.)

Thanks.

**Comment by VincentWo** [comment]
Yes, you are completely right. I should have known that you aware of this distinction, this was a bit of senseless zealotry from my part, sorry.
