### ISSUE TITLE
Allow setting base bidi direction for the text area

### ISSUE THREAD

**Issue by besfahbod** [r12a/uniview#9]
To be able to test the rendering of a text in different base directions, it would be great to be able to set `dir=rtl` on the text area, via a button or something.

**Comment by r12a** [comment]
@besfahbod I just came across this issue. Hadn't seen before, sorry.  Space for buttons in UniView is extremely limited, so i haven't implemented this because it's possible to do that, either:
(a) by using a picker (see the controls below the text area for RTL scripts)
(b) by using browser controls (see https://www.w3.org/International/questions/qa-html-dir.en.html#userexplicit)
